# Generated by Django 2.1.2 on 2018-10-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikaldeiraapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Lore',
        ),
    ]
