# Generated by Django 2.1.2 on 2018-10-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikaldeiraapp', '0002_auto_20181001_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='thumbnail',
            field=models.ImageField(null='False', upload_to='galeria/thumbnail'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='lore',
            name='image',
            field=models.ImageField(null='False', upload_to='galeria/original'),
        ),
    ]
